### ISSUE TITLE
Some minor suggestions

### ISSUE THREAD

**Issue by seanpyre** [Grimelios/LiveSplit.DarkSouls#3]
Few minor suggestions/feedback, since most of the functionality tests have been done by others  (#1, #2):

I did not realize initially that it was intended that the auto split conditions are to be added in the order that you want them to split. This may just be me being used to the behavior of other auto splitters that don't have this restriction, since my only clue that this one works differently is the "manual" option. I also could have misread the documentation, so I apologize if it is there and I just missed it.

I would suggest adding something to the UI (if possible) to indicate the process is hooked successfully or not (similar to DS Gadget).

I think "On Next Load" may work better than making separate conditions for "On Warp" and "On Quitout". I'm not sure what the current implementation is, but a check to see if the character pointer is zero (`CharData1` in DS Gadget) and the current IGT in memory is greater than zero (since it's only zero on the main menu) should suffice for that.

Can't think of anything aside from those, great work on this. I was about to dive into converting my auto splitter (ASL) into a DLL auto splitter, but it looks like that won't be necessary once all the kinks are ironed out of this one. :)

**Comment by seanpyre** [comment]
I knew I forgot some of the suggestions I wanted to give and just remembered them: a split condition for the end of the run (Gwyn on credits screen) and an auto reset condition (on character creation screen).

### Credits Split

This will split on the credits screen after killing Gwyn (regardless of which ending the player picks and it won't split on the cutscenes). I "queue" up the split condition once Gwyn's flag is set, then check if the `charData1Ptr == 0`, `current igt > 0` (not main menu), and if it's a new clear (basically NG+ or playthrough clear count being one greater than when the run started or when Gwyn was killed).

The "clearCount" value is stored as an `int` at `DARKSOULS.exe + 0xF78700, 0x3c`. And for clarity, `charData1Ptr` is `DARKSOULS.exe+0xF7DC70, 4, 0`. 

### Auto Reset on character creation screen

This has been the only decent auto reset condition I've been able to find; this set of conditions seem to only be true when entering the character creation screen (which if a runner does that, it is most likely to be a reset). Here's a pseudo-code-ish snippet:

```
    bool shouldReset = igt.Current == 0;
    shouldReset = shouldReset && charNo.Current    == -1;
    shouldReset = shouldReset && charDex.Current   == 13 && charDex.Changed;
    shouldReset = shouldReset && charSL.Current    == 4 && charSL.Changed;
    shouldReset = shouldReset && charClass.Current == 0;
    shouldReset = shouldReset && charGift.Current  == 0;
```

Basically, it checks for the Warrior class's starting stats with no starting gift if the game is still on the main menus. Probably way overkill, but I've had issues in the past with false resets due to not enough checks (along with timing issues). I don't know exactly how `charNo` works, but it's usually `0` when the game is loaded and `-1` on the main menus. The pointers and offsets for current steam version of these:

```
charNo (int): DARKSOULS.exe+F78700, 8, 8
charClass (byte): DARKSOULS.exe+F78700, 8, 0xC6
charGift (byte): DARKSOULS.exe+F78700, 8, 0xC8
charDex (int): DARKSOULS.exe+F78700, 8, 0x58
charSL (int): DARKSOULS.exe+F78700, 8, 0x88
```

I probably explained this (and my previous comment) horribly - feel free to ask me any questions. If you want to see some of these conditions in action, [here is my ASL autosplitter](https://raw.githubusercontent.com/seanpwolf/AutoSplitters/master/DarkSouls/LiveSplit.DarkSouls.asl) - if anything in that helps you by chance, feel free to use it. :)

**Comment by Grimelios** [comment]
Cool. I'm not sure what I'm going to address first, but I'll keep poking at these issues going forward. Thanks for the detailed help.

**Comment by Grimelios** [comment]
Updates to your points:

- That's an interesting idea to combine "On warp" and "On quitout", but I'm going to keep them separate. To me, that feels clearer as to the intent of each split (plus, they split at different times).

- I don't plan on adding a Credits split either. Event splits with an ending selected already accomplish this (since I updated yesterday to have endings split on credits, rather than when the cutscene begins).

- Auto-reset on the New Game character screen is also a good idea, but I don't plan on adding it either. The reason is that I tend to dislike auto-resets from autosplitters in general. The player might want to queue up a new run while still looking at old splits, or you might accidentally click into the new game screen in the middle of a run.

- Your final point is about adding an indicator for when the process is hooked. This is doable in the layout editor, but not really feasible on the main LiveSplit window itself (due to how LiveSplit restricts component rendering into preset rectangles). Personally, I don't think it would be a very helpful indicator in either case (since you can assume that if the game is running, the process is hooked).

Thank you for the suggestions though :) If you have any others, lemme know.

**Comment by seanpyre** [comment]
> Auto-reset on the New Game character screen is also a good idea, but I don't plan on adding it either. The reason is that I tend to dislike auto-resets from autosplitters in general. The player might want to queue up a new run while still looking at old splits, or you might accidentally click into the new game screen in the middle of a run.

That's fair. The latter scenario may invalidate the run anyway (due to the rules requiring runners to resume gameplay asap after a save and quit - not sure if that scenario would actually break those rules or not), but yeah, this was the only practical auto reset condition I came up with. Ideally, I  think deleting the first save file would be a good condition (since it shows clear intention of resetting), but I never could find anything in memory that would make that work. If you ever did change your mind on this, I think an opt in setting (defaulted to false/off) would be the way to go.

> That's an interesting idea to combine "On warp" and "On quitout", but I'm going to keep them separate. To me, that feels clearer as to the intent of each split (plus, they split at different times).

I was going to remove that idea from my feedback but forgot to - it's not a big deal at all and yeah, is arguably clearer to runners.

> I don't plan on adding a Credits split either. Event splits with an ending selected already accomplish this (since I updated yesterday to have endings split on credits, rather than when the cutscene begins).

That was the main purpose of that suggestion, so no issue there. :)

> Your final point is about adding an indicator for when the process is hooked. This is doable in the layout editor, but not really feasible on the main LiveSplit window itself (due to how LiveSplit restricts component rendering into preset rectangles). Personally, I don't think it would be a very helpful indicator in either case (since you can assume that if the game is running, the process is hooked).

I guess I was a bit unclear - I did mean the layout editor. I only suggested this because I was having issues where the auto splitter didn't hook the game properly failing to read the IGT (maybe it hooked too early?). Also, it could be helpful for debugging/support purposes down the road if you displayed the version detected, but I'm not sure if there are active runners that don't run on the official version (granted the IGT plugin doesn't fully support unofficial versions either, so it's probably a non issue at this point).

> Thank you for the suggestions though :) If you have any others, lemme know.

Will do. :)

**Comment by Grimelios** [comment]
Cool cool. I'll keep all that in mind going forward. Thanks again for the feedback.
